export const REQUEST_WALLET = "REQUEST_WALLET";
export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const SET_WEB3_PROVIDER = "SET_WEB3_PROVIDER";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_NETWORK = "SET_NETWORK";
export const RESET_WEB3_PROVIDER = "RESET_WEB3_PROVIDER";
